name: Development
on:
  push:
    branches:
      - '**' # every branch
      - '!stage*' # exclude branches beginning with stage
jobs:
  build-site:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLIENT_TIMEOUT: "120"
      COMPOSE_HTTP_TIMEOUT: "120"
    steps:
      - uses: actions/checkout@v2
      - name: Compile static site artifacts
        run: |
          export HOST_UID=$(id -u)
          docker-compose -f ./docker-compose.yaml up --build
      - name: Add static site artifacts
        uses: actions/upload-artifact@v2
        with:
          name: static-site
          path: src/_build/html
          retention-days: 1
  publish-docs:
    if: |
      github.event_name == 'push' &&
      (
        github.repository_owner == 'datajoint' ||
        github.repository_owner == 'datajoint-company' ||
        github.repository_owner == 'dj-sciops'
      )
    needs: build-site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch static site artifacts
        uses: actions/download-artifact@v2
        with:
          name: static-site
          path: src/_build/html
      - name: Commit sites changes
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}.git \
              --branch gh-pages --single-branch gh-pages
          rm -R gh-pages/*
          cp -r src/_build/html/* gh-pages/
          cp .gitignore gh-pages/
          touch gh-pages/.nojekyll
          echo "tutorials.datajoint.org" > gh-pages/CNAME
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add . --all
          git commit -m "Update site" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{secrets.GITHUB_TOKEN}}